root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/email_notification.exe ./cmd/api/main.go"
  bin = "./bin/email_notification.exe"
  delay = 1000 
  exclude_dir = ["assets", "tmp", "bin", "vendor", "testdata", "docs"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_regex = ["_test.go"]
  send_interrupt = true
  kill_delay = "500ms"
  log = "air.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false

[screen]
    clear_on_rebuild = true