services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification_network

  api:
    container_name: notification_api_producer
    build:
      context: . 
      dockerfile: ./cmd/api/Dockerfile 
    ports:
      - "8080:8080" 
    environment:
      - API_PORT=:8080
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy 
    networks:
      - notification_network
  
  worker:
    container_name: notification_worker_consumer
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile 
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy 
    restart: on-failure 
    networks:
      - notification_network

networks:
  notification_network:
    driver: bridge

volumes:
  rabbitmq_data: